# Release Build
name: "Build & Release (Main)"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel in-progress runs on new pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool/
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test


  build_android:
    name: Build Android (Release)
    needs: lint_and_test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool/
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Android App (Release)
        run: flutter build apk --release

      - name: Upload Android Release Build
        uses: actions/upload-artifact@v4
        with:
          name: android-release-build
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30

  build_ios:
    name: Build iOS (Release)
    needs: lint_and_test
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool/
            ~/Library/Caches/CocoaPods
            ios/Pods
          key: ${{ runner.os }}-flutter-ios-${{ hashFiles('**/pubspec.lock', '**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-flutter-ios-

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS App (Release)
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -R Runner.app Payload
          zip -r app-release.ipa Payload

      - name: Upload iOS Release Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-build
          path: build/ios/iphoneos/app-release.ipa
          retention-days: 30