# Debug Build
name: "Build & Debug (Dev)"

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build & Debug
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Build Android APK (Debug)
        run: flutter build apk --debug

      - name: Build iOS App (Debug)
        run: |
          flutter build ios --debug --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-debug.ipa Payload

      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/ios/iphoneos/app-debug.ipa



# Release Build
#name: "Build & Release (Dev)"
#
#on:
#  push:
#    branches: [dev]
#  pull_request:
#    branches: [dev]
#
#jobs:
#  build:
#    name: Build & Release
#    runs-on: macos-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/setup-java@v3
#        with:
#          distribution: zulu
#          java-version: 21
#
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#          architecture: x64
#
#      - name: Build Android APK
#        run: flutter build apk --release --split-per-abi
#
#      - name: Build iOS IPA
#        run: |
#          flutter build ios --no-codesign
#          cd build/ios/iphoneos
#          mkdir Payload
#          cd Payload
#          ln -s ../Runner.app
#          cd ..
#          zip -r app.ipa Payload
#
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: |
#            build/app/outputs/apk/release/*
#            build/ios/iphoneos/app.ipa
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.REMOTE_TARGET }}