# Debug Build
name: "Build & Debug (Dev)"

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build & Debug (Dev/Debug)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Build Android App (Debug)
        run: flutter build apk --debug

      - name: Build iOS App (Debug)
        run: |
          flutter build ios --debug --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-debug.ipa Payload

      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/ios/iphoneos/app-debug.ipa